@startuml
Actor User

User -> GUI: Click "Generate" 
GUI -> ControllerApplication: generate(sentence, template, tense)
ControllerApplication -> ApiHandler: getElementsOfTextLemma(sentence) 
ApiHandler -> syntaxApiHandler: Call Syntax API (sentence) 
syntaxApiHandler --> ApiHandler: JSON response 
ApiHandler --> ControllerApplication: List<Pair<String, String>> 
ControllerApplication -> Generator: generateSentences(elements, template, tense)
Generator -> Dictionary: getRandomWord(type) 

Dictionary --> Generator: word 
Generator -> ToxicityApiHandler: getToxicityScoreList(generatedSentences)
ToxicityApiHandler --> Generator:List<Pair<String, Integer>> generatedSentences,ToxicityScore

Generator --> ControllerApplication: List<String> generatedSentences 
ControllerApplication --> GUI: Display generatedSentences
GUI --> User: Show generatedSentences

@enduml