@startuml

ControllerApplication -> ApiHandler: getToxicityScoreList(generatedSentences) 
ApiHandler -> ToxicityApiHandler: Call Toxicity API (for each sentence) 
ToxicityApiHandler --> ApiHandler: JSON response(s) 
ApiHandler --> ControllerApplication: List<Pair<String, Integer>> toxicityScores 

@enduml